#!/usr/bin/env bash

set -euo pipefail

root=$(git rev-parse --show-toplevel)

function download_benchmark_movies_file() {
    curl https://raw.githubusercontent.com/prust/wikipedia-movie-data/master/movies.json | jq -r -c '.[]' > ${root}/testdata/movies.json
    gzip ${root}/testdata/movies.json
}

function main() {
    download_benchmark_movies_file
}

main
